In [4]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n", series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [5]:
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [8]:
data = {
    'Name': ['Daksh','Dinkle','Rohan','Krish'],
    'Age': [19, 19, 20, 18],
    'City': ['Banglore','Banglore','New York','Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0   Daksh   19  Banglore
1  Dinkle   19  Banglore
2   Rohan   20  New York
3   Krish   18   Florida
<class 'pandas.DataFrame'>

In [12]:
data = [
    {'Name': 'Daksh', 'Age': 19, 'City': 'Banglore'},
    {'Name': 'Dinkle', 'Age': 19, 'City': 'Banglore'},
    {'Name': 'Krish', 'Age': 20, 'City': 'Florida'}
]
df = pd.DataFrame(data)
print(df)

     Name  Age      City
0   Daksh   19  Banglore
1  Dinkle   19  Banglore
2   Krish   20   Florida

In [18]:
data = [
    {'Name': 'Daksh', 'Age': 19, 'City': 'Banglore'},
    {'Name': 'Dinkle', 'Age': 19, 'City': 'Banglore'},
    {'Name': 'Krish', 'Age': 20, 'City': 'Florida'}
]
df = pd.DataFrame(data)
print(df)

     Name  Age      City
0   Daksh   19  Banglore
1  Dinkle   19  Banglore
2   Krish   20   Florida

In [19]:
df

     Name  Age      City
0   Daksh   19  Banglore
1  Dinkle   19  Banglore
2   Krish   20   Florida

In [20]:
df['Name']

0     Daksh
1    Dinkle
2     Krish
Name: Name, dtype: str

In [21]:
df.loc[0]

Name       Daksh
Age           19
City    Banglore
Name: 0, dtype: object

In [22]:
df.iloc[0]

Name       Daksh
Age           19
City    Banglore
Name: 0, dtype: object

In [25]:
print(df.at[1,'Age'])

19

In [28]:
df['salary'] = [50000,60000,70000]

In [32]:
df

     Name  Age      City  salary
0   Daksh   19  Banglore   50000
1  Dinkle   19  Banglore   60000
2   Krish   20   Florida   70000

In [36]:
df.drop('Name',axis=1,inplace=True)

In [37]:
df['Age'] = df['Age']+1
df

KeyError: 'Age'